[workspace]
members = ["crates/*"]

[package]
name = "unidoc"
version = "0.1.0"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidoc-parser = { path = "crates/unidoc-parser", version = "0.1" }
unidoc-to-html = { path = "crates/unidoc-to-html", version = "0.1" }

[[test]]
name = "it"
path = "tests/it.rs"
harness = false

[dev-dependencies]
similar = "1.3"
