[package]
name = "unidoc-repr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
detached-str = { path = "../detached-str", version = "0.1" }
slug = "0.1.4"
